---
engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: ".phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      encoding: utf-8
      standard: ".phpcs/WordPress/ruleset.xml"
      ignore_warnings: true
ratings:
  paths:
  # Check all in src except wp-content since it has themes.
  - "src/wp-admin/**.php"
  - "src/wp-includes/**.php"
  - "src/*.php"
exclude_paths:
- .phpcs
- "src/wp-content/**/*"
- tests
- tools
# Exclude directories that cause problems with CodeSniffer
- "src/wp-includes/ID3"
- "**/*.js"
